name: Web Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-automation:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome with extra capabilities
        uses : browser-actions/setup-chrome@v1.4.0
        with :
          chrome-version : latest

      - name : Build with Gradle
        run : |
          chmod +x gradlew
          ./gradlew build

      - name : Run Test
        run : ./gradlew clean test

      - name : Archive test result
        uses : actions/upload-artifact@v4.3.0
        if : always ()
        with :
          name : cucumber
          path : reports/cucumber.html

